### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by tomhosking** [hannahxchen/automatic-paraphrase-dataset-augmentation#1]
Hi, could you please give some documentation on how to use this code? Examples for how to run it on QQP and a new paraphrase dataset would be really useful :)
Thanks

**Comment by hannahxchen** [comment]
Hi, I just updated the README file, which includes how to generate the augmented QQP datasets. Let me know if you have any other questions. :)

**Comment by tomhosking** [comment]
Thanks for the quick response!
